nodes:
  # dummy node to check if db needs to be initialized
  DB_Metadata:
    properties:
      - "initialized"

  # A metadata object for a full search run details
  Run:
    required_properties:
      - "id"
    properties:
      - "start"
      - "end"
      - "openalex_model"
      - "openalex_query_input"
      - "openalex_query_output"
    relationships:
      # This run added this paper
      ADDED:
        - "Paper"

  # A metadata object for a paper
  Paper:
    required_properties:
      - "id"
    properties:
      - "openalex_url"
      - "doi"
      - "title_embedding"
      - "abstract_text"
      - "abstract_embedding"
      - "is_open_access"
      - "pdf_url"
      - "openalex_status"
      - "download_status"
      - "download_error_msg"
      - "grobid_status"
      - "grobid_error_msg"
      - "time_grobid_processed"
      - "time_added"
    relationships:
      REFERENCES:
        - "Paper"

relationships:
  ADDED:
    properties:
      - "rank"
  REFERENCES:
